### PR TITLE
Cleanup and port to Python 3

### PR DESCRIPTION
**Pull request by mcepl**
Just a cleanup and to make sure the script is syntactically Python 3.

### CODE REVIEW

**Review by aspiers — CHANGES_REQUESTED** [review]
Mostly looks great to me, thanks!  But please don't remove files without explaining why in the commit message.  In particular I miss a good explanation to be convinced why it's not worth having the .spec file kept in git, since this can serve as the source of truth and be automatically extracted into the OBS project via a source service.  Then you get all the advantages of using git for managing the .spec file rather than having to use `osc` (which is the whole point of bsgit in the first place).  Or is the idea that bsgit can be used to manage its own build artifacts in git?  If so this deserves to be explained in the commit message.

**Comment by mcepl** [comment]
> In particular I miss a good explanation to be convinced why it's not worth
> having the .spec file kept in git,

I have deep theological/philosophical problems with SPEC files (or debian/ subdirectories) kept in the upstream repositories, besides I think most of what used to be done in Makefiles and such could be done with setup.py these days. However, it is not important, if you insist on *.spec in, I can revert it back.

**Comment by aspiers** [comment]
[**@mcepl**](https://github.com/mcepl) commented on [September 11, 2019 3:39 PM](https://github.com/openSUSE/bsgit/pull/1#issuecomment-530411622 "2019-09-11T14:39:44Z - Replied by Github Reply Comments"):
> > In particular I miss a good explanation to be convinced why it's not worth
> > having the .spec file kept in git,
> 
> I have deep theological/philosophical problems with SPEC files (or debian/ subdirectories) kept in the upstream repositories, besides I think most of what used to be done in Makefiles and such could be done with setup.py these days. However, it is not important, if you insist on *.spec in, I can revert it back.

No I don't insist on that; sorry if I wasn't clear.  I only insist on good commit messages clearly explaining the rationale for changes, otherwise it's difficult or even impossible to review them.

I'm entirely open to being persuaded that spec files, `debian/` etc. don't belong upstream, but I can't be persuaded if I don't hear the reasons ;-)  BTW currently I'm probably 50/50 either way, and indeed genuinely interested in hearing arguments (from both sides).  If the arguments are documented elsewhere then a URL would suffice.  Thanks!

**Comment by mcepl** [comment]
> [**@mcepl**](https://github.com/mcepl) commented on [September 11, 2019 3:39 PM](https://github.com/openSUSE/bsgit/pull/1#issuecomment-530411622):
> I'm entirely open to being persuaded that spec files, ``debian/`` etc. don't belong upstream, but I can't be persuaded if I don't hear the reasons ;-) BTW currently I'm probably 50/50 either way, and indeed genuinely interested in hearing arguments (from both sides). If the arguments are documented elsewhere then a URL would suffice. Thanks!

I am sorry, not much documented, but I have been working for thirteen years now in the Linux distro industry (and before I volunteered for Debian), eleven years in Red Hat and now in SUSE, so it is result of many endless often night (and over the beer ;)) discussions about the philosophy of packaging (sorry, I don’t like using of the word “philosophy” for non-philosophical purposes, but it is late here and I am too tired to think more clearly).

The ideal for me is what *BSD ports (and to some extent in the Linux world Gentoo) do: taking the upstream tarball and then adding just very minimal amount of patches and installation scripts (in *BSD these are actually just Makefiles, IIRC) to make the software work on the system. All patches should go immediately upstream and only very bare minimum is kept in the distribution (actually, if I am not mistaken, originally *BSD didn’t even cache their tarballs, they were downloaded from the upstream every time).

With the more recent distributions it turns out to be smart to save on downloads by caching tarballs (not to slashdot upstream servers and protect against their failure) and even on saving building time by caching binaries and distributing those (which leads to other serious compromises, but that’s another issue).

However, the main point remains: SPEC files (and ``debian/`` directories) should include only very [bear necessities](https://www.youtube.com/results?search_query=bear+necessities), and particularly just things specific for the given distribution (SUSE-, Debian- or Fedora-specific things, metadata etc.). If things are kept this way, maintaining those metadata upstream just doesn’t make sense, and besides it supports unwelcome trend of putting too much intelligence into those SPEC files. All intelligence (aside from some parameters and necessary patches) should be kept upstream (in ``setup.py`` file, for Python packages).

**Comment by aspiers** [comment]
[**@mcepl**](https://github.com/mcepl) commented on [September 11, 2019 7:56 PM](https://github.com/openSUSE/bsgit/pull/1#issuecomment-530517946 "2019-09-11T18:56:45Z - Replied by Github Reply Comments"):
> > [**@mcepl**](https://github.com/mcepl) commented on [September 11, 2019 3:39 PM](https://github.com/openSUSE/bsgit/pull/1#issuecomment-530411622):
> > I'm entirely open to being persuaded that spec files, ``debian/`` etc. don't belong upstream, but I can't be persuaded if I don't hear the reasons ;-) BTW currently I'm probably 50/50 either way, and indeed genuinely interested in hearing arguments (from both sides). If the arguments are documented elsewhere then a URL would suffice. Thanks!
> 
> I am sorry, not much documented, but I have been working for thirteen years now in the Linux distro industry (and before I volunteered for Debian), eleven years in Red Hat and now in SUSE, so it is result of many endless often night (and over the beer ;)) discussions about the philosophy of packaging (sorry, I don’t like using of the word “philosophy” for non-philosophical purposes, but it is late here and I am too tired to think more clearly).

Similar story here ;-)  Have used a Linux desktop exclusively since 1995 (started with Slackware in ~1994, then moved to Red Hat 3.0.3), learnt how to package rpms over the next few years, then joined Novell/SUSE in 2005.  Along the way I've occasionally messed around with Debian and Ubuntu packaging too.

> The ideal for me is what *BSD ports (and to some extent in the Linux world Gentoo) do: taking the upstream tarball and then adding just very minimal amount of patches and installation scripts (in *BSD these are actually just Makefiles, IIRC) to make the software work on the system. All patches should go immediately upstream and only very bare minimum is kept in the distribution (actually, if I am not mistaken, originally *BSD didn’t even cache their tarballs, they were downloaded from the upstream every time).

Yes I agree an "upstream first wherever possible" policy makes sense.

> With the more recent distributions it turns out to be smart to save on downloads by caching tarballs (not to slashdot upstream servers and protect against their failure)

It's not just for saving on downloads; it's required for reproducible builds and in SUSE even for legal reasons IIUC.

>and even on saving building time by caching binaries and distributing those (which leads to other serious compromises, but that’s another issue).
> 
> However, the main point remains: SPEC files (and ``debian/`` directories) should include only very [bear necessities](https://www.youtube.com/results?search_query=bear+necessities), and particularly just things specific for the given distribution (SUSE-, Debian- or Fedora-specific things, metadata etc.). If things are kept this way, maintaining those metadata upstream just doesn’t make sense, and besides it supports unwelcome trend of putting too much intelligence into those SPEC files. All intelligence (aside from some parameters and necessary patches) should be kept upstream (in ``setup.py`` file, for Python packages).

I agree, but I'm not sure how this answers my question.  The debate about how much intelligence to put into spec files or `debian/` directories is independent from the debate about where those spec files or `debian/` directories should *live*.  Even if they are super lightweight, they still have to exist *somewhere*.  My question was about the pros and cons of putting them in the upstream git repo.  You wrote:

>maintaining those metadata upstream just doesn’t make sense

but I missed an explanation of *why* it doesn't make sense.

Again, I'm not necessarily saying it's the best way to do it; just curious why you are against it.

**Comment by mcepl** [comment]
> I agree, but I'm not sure how this answers my question. The debate about how much intelligence to put into spec files or `debian/` directories is independent from the debate about where those spec files or `debian/` directories should _live_. Even if they are super lightweight, they still have to exist _somewhere_. My question was about the pros and cons of putting them in the upstream git repo. You wrote:
> 
> > maintaining those metadata upstream just doesn’t make sense
> 
> but I missed an explanation of _why_ it doesn't make sense.

Right, I thought it is obvious: when the SPEC file (or `debian/` directory etc.) contain only distro-specific data, it should be maintained in a distribution only. Also, anything supporting division of labour between the upstream maintainers and packagers is a good idea IMHO.

Yes, this is slightly only theoretical in case of a distribution-specific tool (I don't see Debian switching to OBS, although there are Debian packages built there), but still I would like to see somebody else maintaining the theoretical package (if anybody cared about this).

**Pull request closed without merging**
